### ISSUE TITLE
governance token digit

### ISSUE THREAD

**Issue by TonyCryptoZ** [cogitoprotocol/cogito-token-contracts#2]
https://github.com/cogitoprotocol/cogito-token-contracts/blob/0de1aeac34d6cc42541714c2328151f8876be68a/contracts/CogitoGovernanceToken.sol#L94

Why this would have 6 digits on governance token compare to 18 digits? typically governance token should have the standard ERC20 digits, and stable coin could have 6 if preferred

**Comment by AlbinaPomogalova** [comment]
The reason for it Cardano blockchain. Sometimes it does not work correctly with 18 decimals. The recomended decimals by Cardano developer is 6. That is the reason
